# Python Fundamentals


This Google Colab notebook develops core Python skills through:

1. Detailed concept explanations
2. Syntax and operation tables
3. Worked examples
4. Common mistakes
5. Guided exercises
6. Independent challenges

## Topics

1. Variables and data types
2. Input, output, and type conversion
3. Arithmetic and comparison operators
4. Strings
5. Lists
6. NumPy arrays
7. Tuples and sets
8. Dictionaries

### Student instructions

- Run the worked examples before starting the exercises.
- Complete only the sections marked `# TODO`.
- Do not hardcode the complete expected output.
- Use meaningful variable names.
- Add at least one new test case to five exercises.
- Read error messages carefully and fix one issue at a time.

In [ ]:
# Run this setup cell once.

from __future__ import annotations

print("Python environment is ready.")

# 1. Variables and Data Types

A **variable** is a named reference to a value stored in memory.

```python
student_name = "Maha"
student_age = 22
student_score = 91.5
is_registered = True
```

Python is **dynamically typed**, which means the type is determined automatically from the assigned value.

## Common Python Data Types

| Type | Example | Meaning |
|---|---|---|
| `int` | `25` | Whole number |
| `float` | `89.5` | Decimal number |
| `str` | `"Python"` | Text |
| `bool` | `True` | Logical value |
| `NoneType` | `None` | Missing or unassigned value |

## Variable Naming Rules

Valid:
```python
student_name = "Sara"
course_score = 95
level_2 = True
```

Invalid:
```python
2level = 4        # Cannot begin with a digit
student-name = 1  # Hyphen is not allowed
class = "AI"      # Reserved keyword
```

## Naming Recommendations

Use meaningful `snake_case` names:

```python
final_score = 92
number_of_students = 30
```

## Important Operations

| Operation | Example | Result |
|---|---|---|
| Assignment | `age = 22` | Stores `22` |
| Multiple assignment | `x, y = 10, 20` | Assigns two values |
| Swap values | `x, y = y, x` | Exchanges values |
| Check type | `type(age)` | Returns the type |
| Check identity | `id(age)` | Returns object identity |
| Delete variable | `del age` | Removes the name |

## Worked Example 1 — Creating Variables

In [ ]:
student_name = "Sara"
student_age = 21
student_gpa = 4.65
is_registered = True
middle_name = None

print("Name:", student_name)
print("Age:", student_age)
print("GPA:", student_gpa)
print("Registered:", is_registered)
print("Middle name:", middle_name)

## Worked Example 2 — Checking Data Types

In [ ]:
course_name = "Python Fundamentals"
number_of_students = 28
average_score = 87.4
is_completed = False

print(type(course_name))
print(type(number_of_students))
print(type(average_score))
print(type(is_completed))

## Worked Example 3 — Multiple Assignment and Swapping

In [ ]:
first_value = 10
second_value = 25

print("Before:", first_value, second_value)

first_value, second_value = second_value, first_value

print("After:", first_value, second_value)

## Common Mistakes

1. Using a variable before assigning a value:
```python
print(score)  # NameError if score was not created
```

2. Confusing text and numbers:
```python
age = "22"  # This is text, not an integer
```

3. Using unclear names:
```python
x = 95
```

A clearer version:
```python
final_exam_score = 95
```

## Exercises — Variables and Data Types

### Exercise 1: Create a Student Profile

**Level:** Basic  
**Learning objective:** Create variables using appropriate data types.

#### Task
Create variables for name, age, GPA, registration status, and optional middle name. Print every value.

#### Expected output
```text
Name: Maha
Age: 22
GPA: 4.75
Registered: True
Middle name: None
```

<details>
<summary><strong>Hint</strong></summary>

Use `str`, `int`, `float`, `bool`, and `None`.

</details>

In [1]:
# TODO: Create five variables.

name = "Maha"
age = 22
GPA = 4.75
registered = True
middle_name = None

# TODO: Print the values.

print("Name:", name)
print("Age:", age)
print("GPA:", GPA)
print("Registered:", registered)
print("Middle name:", middle_name)

Name: Maha
Age: 22
GPA: 4.75
Registered: True
Middle name: None


### Exercise 2: Identify Data Types

**Level:** Basic  
**Learning objective:** Use `type()` to inspect values.

#### Task
Print the type of each variable.

#### Expected output
```text
<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>
```

<details>
<summary><strong>Hint</strong></summary>

Pass each variable to `type()`.

</details>

In [3]:
course = "Python"
students = 30
average = 88.5
active = True

# TODO: Print each type.

print(type(course))
print(type(students))
print(type(average))
print(type(active))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>


### Exercise 3: Multiple Assignment

**Level:** Basic  
**Learning objective:** Assign several values in one statement.

#### Task
Create `name`, `age`, and `major` in one line, then print them.

#### Expected output
```text
Maha 22 Artificial Intelligence
```

<details>
<summary><strong>Hint</strong></summary>

Use `name, age, major = ...`.

</details>

In [4]:
# TODO: Assign three variables in one line.
name,age, major = "Maha", 22, "Artificial Intelligence"

# TODO: Print them.
print(name, age, major, sep=" ")

Maha 22 Artificial Intelligence


### Exercise 4: Swap Two Values

**Level:** Basic  
**Learning objective:** Use Python tuple assignment to swap variables.

#### Task
Swap the values without creating a third variable.

#### Expected output
```text
Before: 15 40
After: 40 15
```

<details>
<summary><strong>Hint</strong></summary>

Use `first, second = second, first`.

</details>

In [5]:
first = 15
second = 40

print("Before:", first, second)

# TODO: Swap the values.
first, second = second, first

print("After:", first, second)

Before: 15 40
After: 40 15


### Exercise 5: Update a Variable

**Level:** Basic  
**Learning objective:** Understand that assigning a new value replaces the previous value.

#### Task
Start with `score = 75`, add 10 bonus points, then print the new score.

#### Expected output
```text
Updated score: 85
```

<details>
<summary><strong>Hint</strong></summary>

Use `score = score + 10` or `score += 10`.

</details>

In [6]:
score = 75

# TODO: Add 10 points.
score += 10

print("Updated score:", score)

Updated score: 85


### Exercise 6: Choose Appropriate Types

**Level:** Intermediate  
**Learning objective:** Select suitable types for real-world data.

#### Task
Create variables for product name, price, quantity, availability, and missing discount code.

#### Expected output
```text
Wireless Mouse
85.5
3
True
None
```

<details>
<summary><strong>Hint</strong></summary>

Use one value from each major basic type.

</details>

In [7]:
# TODO: Create the five variables.
product_name = "Wireless Mouse"
price = 85.5
quantity = 3
availability = True
missing_discount_code = None

# TODO: Print each value.
print(product_name)
print(price)
print(quantity)
print(availability)
print(missing_discount_code)

Wireless Mouse
85.5
3
True
None


# 2. Input, Output, and Type Conversion

Programs usually follow a simple pattern:

1. **Receive data** from the user or another source.
2. **Convert and process** the data.
3. **Display the result** in a clear format.

---

## 2.1 Displaying Output with `print()`

The `print()` function displays text, variables, and calculated values.

```python
print("Welcome to Python")
print(25)
print("Score:", 95)
```

You can print more than one value in the same statement:

```python
name = "Maha"
score = 92

print(name, score)
```

### Important `print()` Parameters

| Parameter | Purpose | Example |
|---|---|---|
| `sep` | Changes the separator between values | `print("A", "B", sep="-")` |
| `end` | Changes what appears after the output | `print("Hello", end=" ")` |
| `file` | Sends output to a file instead of the screen | Used later in file handling |

The default separator is one space, and the default ending is a new line.

## Worked Example 1 — Basic Output, `sep`, and `end`

In [ ]:
course = "Python"
week = 2
students = 30

print("Course:", course)
print("Week:", week)
print("Students:", students)

print("Python", "Data", "AI", sep=" | ")

print("Welcome", end=" ")
print("to the course")

### Explanation

```python
print("Python", "Data", "AI", sep=" | ")
```

uses ` | ` instead of a normal space.

```python
print("Welcome", end=" ")
```

does not move immediately to a new line. The following `print()` continues on the same line.

---

## 2.2 Reading Input with `input()`

The `input()` function pauses the program and waits for the user to enter a value.

```python
name = input("Enter your name: ")
```

The text inside the parentheses is called the **prompt**.

### Critical Rule

`input()` always returns a string, even when the user enters digits.

```python
age = input("Enter your age: ")
print(type(age))
# <class 'str'>
```

For automatic notebook execution, the examples below use sample text values. During class, replace the sample with an actual `input()` call.

## Worked Example 2 — Reading and Using Text Input

In [ ]:
# Live classroom version:
# student_name = input("Enter your name: ")

student_name = "Maha"

print("Welcome,", student_name)
print("Number of characters:", len(student_name))

## 2.3 Converting Between Data Types

Because `input()` returns text, numeric input must usually be converted before calculation.

| Function | Conversion | Example | Result |
|---|---|---|---|
| `int()` | Value to integer | `int("25")` | `25` |
| `float()` | Value to decimal number | `float("85.5")` | `85.5` |
| `str()` | Value to string | `str(100)` | `"100"` |
| `bool()` | Value to Boolean | `bool(1)` | `True` |

### Common Numeric Conversion

```python
age_text = "22"
age = int(age_text)
```

```python
price_text = "85.50"
price = float(price_text)
```

### Important Difference

```python
"5" + "3"
```

produces:

```text
53
```

because both values are strings.

```python
int("5") + int("3")
```

produces:

```text
8
```

## Worked Example 3 — Input, Conversion, and Calculation

In [ ]:
# Live classroom version:
# price_text = input("Enter the price: ")
# quantity_text = input("Enter the quantity: ")

price_text = "80.0"
quantity_text = "3"

price = float(price_text)
quantity = int(quantity_text)
total = price * quantity

print("Price type before conversion:", type(price_text))
print("Price type after conversion:", type(price))
print("Total:", total)

## 2.4 Formatted Output with f-Strings

An **f-string** allows variables and expressions to be placed directly inside text.

```python
name = "Sara"
score = 92

print(f"{name} scored {score}.")
```

Expressions can also appear inside braces:

```python
price = 100
quantity = 3

print(f"Total: {price * quantity}")
```

### Number Formatting

| Format | Meaning | Example result |
|---|---|---|
| `{value:.2f}` | Two decimal places | `85.50` |
| `{value:.1f}` | One decimal place | `85.5` |
| `{value:,}` | Thousands separator | `1,000,000` |
| `{rate:.0%}` | Percentage | `15%` |
| `{value:>10}` | Right-align in width 10 | Useful in reports |

## Worked Example 4 — f-Strings and Numeric Formatting

In [ ]:
student_name = "Nora"
score = 92.4567
price = 1250
discount_rate = 0.15

print(f"Student: {student_name}")
print(f"Score: {score:.2f}")
print(f"Price: {price:,.2f} SAR")
print(f"Discount: {discount_rate:.0%}")

## 2.5 Converting Values to Text

`str()` is useful when text must be built from non-string values.

```python
age = 22
message = "Age: " + str(age)
```

An f-string is usually more readable:

```python
message = f"Age: {age}"
```

## Worked Example 5 — Building a Complete Receipt

In [ ]:
item = "Keyboard"
price = 180.0
quantity = 2
tax_rate = 0.15

subtotal = price * quantity
tax = subtotal * tax_rate
final_total = subtotal + tax

print("Purchase Receipt")
print("-" * 30)
print(f"Item: {item}")
print(f"Price: {price:.2f} SAR")
print(f"Quantity: {quantity}")
print(f"Subtotal: {subtotal:.2f} SAR")
print(f"Tax: {tax:.2f} SAR")
print(f"Final total: {final_total:.2f} SAR")

## Common Mistakes

### Mistake 1 — Calculating with Unconverted Input

```python
quantity = "3"
price = 80

total = quantity * price
```

This does not perform normal numeric multiplication.

Correct:

```python
quantity = int("3")
price = 80

total = quantity * price
```

### Mistake 2 — Converting Invalid Text

```python
int("Python")
```

raises `ValueError` because the text is not a valid integer.

### Mistake 3 — Confusing `int()` and `float()`

```python
int("85.5")
```

raises an error because `"85.5"` is not an integer-form string.

Use:

```python
float("85.5")
```

### Mistake 4 — Forgetting Formatting

```python
price = 85.5
print(price)
```

displays `85.5`.

For money:

```python
print(f"{price:.2f}")
```

displays `85.50`.

## Exercises — Input, Output, and Conversion

### Exercise 7: Formatted Profile

**Level:** Basic  
**Learning objective:** Use `print()` and f-strings.

#### Task
Print the variables using the required format.

#### Expected output
```text
Student: Sara
Major: Computer Science
Level: 3
```

<details>
<summary><strong>Hint</strong></summary>

Use one f-string per line.

</details>

In [8]:
name = "Sara"
major = "Computer Science"
level = 3

# TODO: Print the profile.
print(f"Student: {name}")
print(f"Major: {major}")
print(f"Level: {level}")

Student: Sara
Major: Computer Science
Level: 3


### Exercise 8: Print with Custom Separator

**Level:** Basic  
**Learning objective:** Use the `sep` parameter.

#### Task
Print the date values separated by `/`.

#### Expected output
```text
13/7/2026
```

<details>
<summary><strong>Hint</strong></summary>

Pass `sep='/'` to `print()`.

</details>

In [9]:
day = 13
month = 7
year = 2026

# TODO: Print the date.
print(day, month, year, sep="/")

13/7/2026


### Exercise 9: Convert Text to Numbers

**Level:** Basic  
**Learning objective:** Convert numeric strings before calculation.

#### Task
Convert the values and calculate the total.

#### Expected output
```text
Total: 240.0
```

<details>
<summary><strong>Hint</strong></summary>

Use `float()` for price and `int()` for quantity.

</details>

In [13]:
price_text = "80.0"
quantity_text = "3"

# TODO: Convert and calculate.
price_int = float(price_text)
quantity_int = int(quantity_text)

# TODO: Print the total.
print(f"Total: {(price_int * quantity_int):.1f}")

Total: 240.0


### Exercise 10: Interactive Rectangle

**Level:** Intermediate  
**Learning objective:** Read user input and convert it.

#### Task
Ask for length and width, then print area and perimeter.

#### Expected output
```text
Example for length=8 and width=5:
Area: 40.0
Perimeter: 26.0
```

<details>
<summary><strong>Hint</strong></summary>

Convert both inputs with `float()`.

</details>

In [14]:
# TODO: Ask the user for length and width.
length = input("input length")
width = input("input width")

# TODO: Calculate area and perimeter.
area = float(length) * float(width)
perimeter = 2 * (float(length) + float(width))

# TODO: Print the results.
print(f"Example for length={length} and width={width}:")
print(f"Area: {area:.1f}")
print(f"Perimeter: {perimeter:.1f}")

Example for length=8 and width=5:
Area: 40.0
Perimeter: 26.0


### Exercise 11: Temperature Input

**Level:** Intermediate  
**Learning objective:** Read input, convert it, and apply a formula.

#### Task
Read Celsius and convert to Fahrenheit.

#### Expected output
```text
Example for 30:
Fahrenheit: 86.0
```

<details>
<summary><strong>Hint</strong></summary>

Formula: `(celsius * 9 / 5) + 32`.

</details>

In [15]:
# TODO: Read Celsius from the user.
celsius = input("enter degree in Celsius")

# TODO: Convert and calculate Fahrenheit.
fahrenheit = (float(celsius) * 9 / 5) + 32

# TODO: Print the result.
print(f"Example for {celsius}:")
print(f"Fahrenheit: {fahrenheit:.1f}")

Example for 30:
Fahrenheit: 86.0


### Exercise 12: Receipt Formatting

**Level:** Intermediate  
**Learning objective:** Format numbers to two decimal places.

#### Task
Print the receipt exactly.

#### Expected output
```text
Item: Keyboard
Price: 180.00 SAR
Quantity: 2
Total: 360.00 SAR
```

<details>
<summary><strong>Hint</strong></summary>

Use `:.2f` inside f-strings.

</details>

In [16]:
item = "Keyboard"
price = 180
quantity = 2
total = price * quantity

# TODO: Calculate and print the receipt.
print(f"Item: {item}")
print(f"Price: {price:.2f} SAR")
print(f"Quantity: {quantity}")
print(f"Total: {total:.2f} SAR")

Item: Keyboard
Price: 180.00 SAR
Quantity: 2
Total: 360.00 SAR


# 3. Arithmetic and Comparison Operators

## Arithmetic Operators

| Operator | Meaning | Example |
|---|---|---|
| `+` | Addition | `10 + 3` |
| `-` | Subtraction | `10 - 3` |
| `*` | Multiplication | `10 * 3` |
| `/` | Division | `10 / 3` |
| `//` | Floor division | `10 // 3` |
| `%` | Remainder | `10 % 3` |
| `**` | Power | `10 ** 2` |

## Comparison Operators

| Operator | Meaning |
|---|---|
| `==` | Equal |
| `!=` | Not equal |
| `>` | Greater than |
| `<` | Less than |
| `>=` | Greater than or equal |
| `<=` | Less than or equal |

Comparison operations return `True` or `False`.

## Logical Operators

| Operator | Meaning |
|---|---|
| `and` | Both conditions must be true |
| `or` | At least one condition must be true |
| `not` | Reverses a Boolean result |

## Assignment Operators

| Operator | Equivalent |
|---|---|
| `x += 5` | `x = x + 5` |
| `x -= 5` | `x = x - 5` |
| `x *= 5` | `x = x * 5` |
| `x /= 5` | `x = x / 5` |

## Worked Example 1 — Arithmetic Operations

In [ ]:
first_number = 17
second_number = 5

print("Addition:", first_number + second_number)
print("Subtraction:", first_number - second_number)
print("Multiplication:", first_number * second_number)
print("Division:", first_number / second_number)
print("Floor division:", first_number // second_number)
print("Remainder:", first_number % second_number)
print("Power:", first_number ** second_number)

## Worked Example 2 — Comparisons and Logical Operators

In [ ]:
score = 88
attendance = 92

passed_score = score >= 60
passed_attendance = attendance >= 75
course_passed = passed_score and passed_attendance

print("Passed score requirement:", passed_score)
print("Passed attendance requirement:", passed_attendance)
print("Passed course:", course_passed)

## Operator Precedence

Python follows an order of operations:

1. Parentheses `()`
2. Powers `**`
3. Multiplication, division, floor division, remainder
4. Addition and subtraction
5. Comparisons
6. Logical operators

Example:

```python
result = 2 + 3 * 4
# 14
```

Using parentheses:

```python
result = (2 + 3) * 4
# 20
```

## Exercises — Arithmetic and Comparisons

### Exercise 13: Complete Arithmetic Report

**Level:** Basic  
**Learning objective:** Use all arithmetic operators.

#### Task
Print the seven arithmetic results for 17 and 5.

#### Expected output
```text
Addition: 22
Subtraction: 12
Multiplication: 85
Division: 3.4
Floor division: 3
Remainder: 2
Power: 1419857
```

<details>
<summary><strong>Hint</strong></summary>

Use the provided variables for every calculation.

</details>

In [18]:
first_number = 17
second_number = 5

# TODO: Print all results.
print(f"Addition: {first_number + second_number}")
print(f"Subtraction: {first_number - second_number}")
print(f"Multiplication: {first_number * second_number}")
print(f"Division: {float(first_number) / float(second_number)}")
print(f"Floor division: {first_number // second_number}")
print(f"Remainder: {first_number % second_number}")
print(f"Power: {first_number ** second_number}")

Addition: 22
Subtraction: 12
Multiplication: 85
Division: 3.4
Floor division: 3
Remainder: 2
Power: 1419857


### Exercise 14: Even or Odd

**Level:** Basic  
**Learning objective:** Use the remainder operator.

#### Task
Determine whether the number is even.

#### Expected output
```text
Number: 42
Even: True
```

<details>
<summary><strong>Hint</strong></summary>

An even number has remainder `0` when divided by `2`.

</details>

In [19]:
number = 42

# TODO: Create a Boolean result.
is_even = True if number % 2 == 0 else False

print("Number:", number)
print("Even:", is_even)

Number: 42
Even: True


### Exercise 15: Eligibility Check

**Level:** Intermediate  
**Learning objective:** Combine comparisons with `and`.

#### Task
A student is eligible when score is at least 80 and attendance is at least 75.

#### Expected output
```text
Eligible: True
```

<details>
<summary><strong>Hint</strong></summary>

Create two comparisons and combine them.

</details>

In [20]:
score = 85
attendance = 90

# TODO: Calculate eligibility.
is_eligible = True if score >= 80 and attendance >= 75 else False
print("Eligible:", is_eligible)

Eligible: True


### Exercise 16: Discount and Tax

**Level:** Intermediate  
**Learning objective:** Perform a multi-step financial calculation.

#### Task
Apply a 10% discount and then 15% tax.

#### Expected output
```text
Subtotal: 500.00 SAR
Discount: 50.00 SAR
After discount: 450.00 SAR
Tax: 67.50 SAR
Final total: 517.50 SAR
```

<details>
<summary><strong>Hint</strong></summary>

Calculate each stage in a separate variable.

</details>

In [23]:
subtotal = 500
discount_rate = 0.10
tax_rate = 0.15

discounted_amount = subtotal * discount_rate
taxed_amount =  (subtotal - discounted_amount) * tax_rate

# TODO: Calculate and print all stages.
print(f"Subtotal: {subtotal:.2f} SAR")
print(f"Discount: {discounted_amount :.2f} SAR")
print(f"After Discount: {(subtotal - discounted_amount):.2f} SAR")
print(f"Tax: {taxed_amount:.2f} SAR")
print(f"Final Total: {subtotal - discounted_amount + taxed_amount:.2f} SAR")

Subtotal: 500.00 SAR
Discount: 50.00 SAR
After Discount: 450.00 SAR
Tax: 67.50 SAR
Final Total: 517.50 SAR


### Exercise 17: Range Validation

**Level:** Intermediate  
**Learning objective:** Use chained comparisons.

#### Task
Check whether the score is between 0 and 100 inclusive.

#### Expected output
```text
Valid score: True
```

<details>
<summary><strong>Hint</strong></summary>

Python supports `0 <= score <= 100`.

</details>

In [24]:
score = 92

# TODO: Validate the score.
is_valid = True if score >= 0 and score <= 100 else False

print("Valid score:", is_valid)

Valid score: True


### Exercise 18: Operator Precedence

**Level:** Intermediate  
**Learning objective:** Use parentheses to control calculation order.

#### Task
Create two results using the same numbers but different grouping.

#### Expected output
```text
Without parentheses: 14
With parentheses: 20
```

<details>
<summary><strong>Hint</strong></summary>

Compare `2 + 3 * 4` with `(2 + 3) * 4`.

</details>

In [25]:
# TODO: Calculate both results.
without_parentheses = 2 + 3 * 4
with_parentheses = (2 + 3) * 4

# TODO: Print them.
print(f"Without parentheses: {without_parentheses}")
print(f"With parentheses: {with_parentheses}")

Without parentheses: 14
With parentheses: 20


# 4. Strings

A **string** is an ordered sequence of characters.

```python
message = "Python"
```

Strings are **immutable**, meaning individual characters cannot be changed directly.

## Indexing

```python
word = "Python"
word[0]   # P
word[-1]  # n
```

## Slicing

```python
word[0:3]  # Pyt
word[:3]   # Pyt
word[3:]   # hon
word[::-1] # nohtyP
```

## Common String Methods

| Method | Purpose |
|---|---|
| `.lower()` | Lowercase |
| `.upper()` | Uppercase |
| `.title()` | Title case |
| `.strip()` | Remove surrounding spaces |
| `.replace()` | Replace text |
| `.split()` | Split into a list |
| `.join()` | Join strings |
| `.startswith()` | Check beginning |
| `.endswith()` | Check ending |
| `.find()` | Find position |
| `.count()` | Count occurrences |
| `.isalpha()` | Letters only |
| `.isdigit()` | Digits only |
| `.isalnum()` | Letters and digits |

## Worked Example 1 — Cleaning and Transforming Text

In [ ]:
raw_name = "   maha altalk   "

clean_name = raw_name.strip().title()

print("Original:", repr(raw_name))
print("Cleaned:", clean_name)
print("Uppercase:", clean_name.upper())
print("Lowercase:", clean_name.lower())
print("Length:", len(clean_name))

## Worked Example 2 — Splitting and Joining

In [ ]:
sentence = "Python supports data analysis"

words = sentence.split()
joined_with_dash = "-".join(words)

print("Words:", words)
print("Number of words:", len(words))
print("Joined:", joined_with_dash)

## Worked Example 3 — Searching and Replacing

In [ ]:
message = "Python is simple and Python is powerful"

print("Count:", message.count("Python"))
print("Starts with Python:", message.startswith("Python"))
print("Position of simple:", message.find("simple"))
print("Updated:", message.replace("simple", "readable"))

## Common Mistakes

1. Index out of range:
```python
word = "AI"
print(word[5])
```

2. Trying to modify one character:
```python
word[0] = "a"  # TypeError
```

Correct approach:
```python
word = "a" + word[1:]
```

## Exercises — Strings

### Exercise 19: String Indexing

**Level:** Basic  
**Learning objective:** Access characters using positive and negative indexes.

#### Task
Print the first, third, and last characters.

#### Expected output
```text
First: P
Third: t
Last: n
```

<details>
<summary><strong>Hint</strong></summary>

Use indexes `0`, `2`, and `-1`.

</details>

In [26]:
word = "Python"

# TODO: Print the requested characters.
print(f"First: {word[0]}")
print(f"Third: {word[2]}")
print(f"Last: {word[-1]}")

First: P
Third: t
Last: n


### Exercise 20: String Slicing

**Level:** Basic  
**Learning objective:** Extract parts of a string.

#### Task
Print first four, last four, reverse, and every second character.

#### Expected output
```text
First four: PROG
Last four: MING
Reverse: GNIMMARGORP
Every second: PORMN
```

<details>
<summary><strong>Hint</strong></summary>

Use slicing with start, stop, and step.

</details>

In [27]:
word = "PROGRAMMING"

# TODO: Print all slices.
print("First four:", word[:3])
print("Last four:", word[-3:])
print("Reverse:", word[::-1])
print("Every second:", word[::2])

First four: PRO
Last four: ING
Reverse: GNIMMARGORP
Every second: PORMIG


### Exercise 21: Clean a Full Name

**Level:** Basic  
**Learning objective:** Use `strip()` and `title()`.

#### Task
Clean and format the name.

#### Expected output
```text
Full name: Maha Abdullah Altalk
```

<details>
<summary><strong>Hint</strong></summary>

Chain the two methods.

</details>

In [29]:
full_name = "   maha abdullah altalk   "
stripped_name = full_name.strip()
formatted_name = stripped_name.title()

# TODO: Clean and print the name.
print("Full name:", formatted_name)

Full name: Maha Abdullah Altalk


### Exercise 22: Create Initials

**Level:** Intermediate  
**Learning objective:** Combine splitting, indexing, and joining.

#### Task
Return the initials.

#### Expected output
```text
Initials: MAA
```

<details>
<summary><strong>Hint</strong></summary>

Take the first character from every word.

</details>

In [30]:
full_name = "Maha Abdullah Altalk"
split_name = full_name.split(" ")

# TODO: Create initials.
initials = ""
for word in split_name:
    initials += word[0]

print("Initials:", initials)

Initials: MAA


### Exercise 23: Word Count

**Level:** Intermediate  
**Learning objective:** Split text and count words.

#### Task
Print the list and the word count.

#### Expected output
```text
Words: ['Python', 'makes', 'programming', 'clear']
Count: 4
```

<details>
<summary><strong>Hint</strong></summary>

Use `.split()` and `len()`.

</details>

In [31]:
sentence = "Python makes programming clear"

# TODO: Split and count.
split_sentence = sentence.split(" ")
print(len(split_sentence))

4


### Exercise 24: Count a Word

**Level:** Intermediate  
**Learning objective:** Normalize case and count occurrences.

#### Task
Count `python` regardless of case.

#### Expected output
```text
Python count: 3
```

<details>
<summary><strong>Hint</strong></summary>

Convert the sentence to lowercase before counting.

</details>

In [32]:
sentence = "Python is useful. I study python. PYTHON is popular."
normalized_sentence = sentence.lower()
# TODO: Normalize and count.

print("Python count:", normalized_sentence.count("python"))

Python count: 3


### Exercise 25: Palindrome Check

**Level:** Intermediate  
**Learning objective:** Compare a string with its reverse.

#### Task
Check whether the cleaned word is a palindrome.

#### Expected output
```text
Palindrome: True
```

<details>
<summary><strong>Hint</strong></summary>

Lowercase the word and compare it with `[::-1]`.

</details>

In [34]:
word = "Level"
normalized_sentence = word.lower()

# TODO: Normalize and check.
is_palindrome = True
start = 0
end = len(normalized_sentence) - 1
while start < end:
    if normalized_sentence[start] != normalized_sentence[end]:
        is_palindrome = False
    start += 1
    end -= 1

print("Palindrome:", is_palindrome)

Palindrome: True


### Exercise 26: Email Components

**Level:** Intermediate+  
**Learning objective:** Split an email address into username and domain.

#### Task
Print both parts.

#### Expected output
```text
Username: student.name
Domain: university.edu
```

<details>
<summary><strong>Hint</strong></summary>

Use `.split('@')` with tuple unpacking.

</details>

In [35]:
email = "student.name@university.edu"

# TODO: Split and print.
split_email = email.split("@")
print("Username:", split_email[0])
print("Domain:", split_email[1])

Username: student.name
Domain: university.edu


### Exercise 27: Character Classification

**Level:** Intermediate+  
**Learning objective:** Count letters, digits, spaces, and special characters.

#### Task
Analyze the text.

#### Expected output
```text
Letters: 6
Digits: 3
Spaces: 1
Special: 1
```

<details>
<summary><strong>Hint</strong></summary>

Loop through characters and use `isalpha()`, `isdigit()`, and `isspace()`.

</details>

In [36]:
text = "Python 123!"

letters = 0
digits = 0
spaces = 0
special = 0

# TODO: Count each category.
for char in text:
    if char.isalpha():
        letters += 1
    elif char.isdigit():
        digits += 1
    elif char.isspace():
        spaces += 1
    else:
        special += 1

print("Letters:", letters)
print("Digits:", digits)
print("Spaces:", spaces)
print("Special:", special)

Letters: 6
Digits: 3
Spaces: 1
Special: 1


# 5. Lists

A **list** is an ordered and mutable collection.

```python
scores = [80, 90, 75]
```

Lists:
- preserve order,
- allow duplicates,
- can contain different data types,
- can be modified.

## List Operations

| Operation | Example |
|---|---|
| Create | `values = [1, 2, 3]` |
| Access | `values[0]` |
| Slice | `values[1:3]` |
| Update | `values[0] = 10` |
| Add one | `values.append(4)` |
| Add many | `values.extend([5, 6])` |
| Insert | `values.insert(1, 20)` |
| Remove by value | `values.remove(2)` |
| Remove by index | `values.pop(0)` |
| Clear | `values.clear()` |
| Sort | `values.sort()` |
| Reverse | `values.reverse()` |
| Count | `values.count(2)` |
| Find index | `values.index(3)` |
| Copy | `values.copy()` |

## Worked Example 1 — List Methods

In [ ]:
courses = ["Python", "SQL", "Git"]

courses.append("Cloud")
courses.insert(1, "Data Analysis")
courses.remove("Git")

print("Courses:", courses)
print("Count:", len(courses))
print("Python index:", courses.index("Python"))

## Worked Example 2 — Filtering with a Loop

In [ ]:
scores = [45, 78, 60, 52, 91, 66]

passing_scores = []

for score in scores:
    if score >= 60:
        passing_scores.append(score)

print("Passing scores:", passing_scores)

## Worked Example 3 — List Comprehension

In [ ]:
numbers = list(range(1, 11))

even_squares = [
    number ** 2
    for number in numbers
    if number % 2 == 0
]

print(even_squares)

## Copying Lists

This does not create an independent copy:

```python
first = [1, 2, 3]
second = first
```

Both names refer to the same list.

Use:

```python
second = first.copy()
```

## Exercises — Lists

### Exercise 28: Access and Slice a List

**Level:** Basic  
**Learning objective:** Use indexing and slicing.

#### Task
Print first, last, first three, and last three items.

#### Expected output
```text
First: 10
Last: 60
First three: [10, 20, 30]
Last three: [40, 50, 60]
```

<details>
<summary><strong>Hint</strong></summary>

Use indexes and slices.

</details>

In [38]:
numbers = [10, 20, 30, 40, 50, 60]

# TODO: Print the requested values.
print("First: ", numbers[0])
print("Last: ", numbers[-1])
print("First Three: ", numbers[:3])
print("Last Three: ", numbers[-3:])

First:  10
Last:  60
First Three:  [10, 20, 30]
Last Three:  [40, 50, 60]


### Exercise 29: Modify a Skills List

**Level:** Basic  
**Learning objective:** Use append, insert, remove, and sorting.

#### Task
Add `Git`, insert `SQL`, remove `HTML`, then sort.

#### Expected output
```text
['Git', 'Python', 'SQL']
```

<details>
<summary><strong>Hint</strong></summary>

Apply operations in the given order.

</details>

In [44]:
skills = ["Python", "HTML"]

# TODO: Modify the list.
skills.append("Git")
skills.insert(1, "SQL")
skills.remove("HTML")
skills.sort()

print(skills)

['Git', 'Python', 'SQL']


### Exercise 30: List Statistics

**Level:** Basic  
**Learning objective:** Use built-in numeric functions.

#### Task
Print count, total, minimum, maximum, and average.

#### Expected output
```text
Count: 5
Total: 425
Minimum: 70
Maximum: 100
Average: 85.0
```

<details>
<summary><strong>Hint</strong></summary>

Use `len`, `sum`, `min`, and `max`.

</details>

In [46]:
scores = [70, 85, 90, 80, 100]
length_scores = len(scores)
sum_scores = sum(scores)
min_scores = min(scores)
max_scores = max(scores)
average_scores = float(sum_scores) / length_scores

# TODO: Calculate statistics.
print(f"Count: {length_scores}\nTotal: {sum_scores}\nMinimum: {min_scores}\nMaximum: {max_scores}\nAverage: {average_scores}")

Count: 5
Total: 425
Minimum: 70
Maximum: 100
Average: 85.0


### Exercise 31: Filter Passing Scores

**Level:** Intermediate  
**Learning objective:** Build a new list using a condition.

#### Task
Keep scores greater than or equal to 60.

#### Expected output
```text
[78, 60, 91, 66]
```

<details>
<summary><strong>Hint</strong></summary>

Use a loop and `append()`.

</details>

In [47]:
scores = [45, 78, 60, 52, 91, 66]
passing_scores = []

# TODO: Build the list.
for item in scores:
    if item >= 60:
        passing_scores.append(item)

print(passing_scores)

[78, 60, 91, 66]


### Exercise 32: Remove Duplicates

**Level:** Intermediate  
**Learning objective:** Preserve first appearance order.

#### Task
Remove repeated values.

#### Expected output
```text
['Python', 'SQL', 'Git', 'Cloud']
```

<details>
<summary><strong>Hint</strong></summary>

Check membership before appending.

</details>

In [48]:
skills = ["Python", "SQL", "Python", "Git", "SQL", "Cloud"]
unique_skills = []

# TODO: Remove duplicates.
for item in skills:
    if item not in unique_skills:
        unique_skills.append(item)

print(unique_skills)

['Python', 'SQL', 'Git', 'Cloud']


### Exercise 33: Second Highest Unique Score

**Level:** Intermediate  
**Learning objective:** Combine uniqueness and sorting.

#### Task
Find the second highest unique value.

#### Expected output
```text
Second highest: 92
```

<details>
<summary><strong>Hint</strong></summary>

Use `set()`, `sorted()`, and negative indexing.

</details>

In [54]:
scores = [88, 95, 72, 95, 92, 81]
scores.sort()
unique_skills = set(scores)
unique_skills = list(unique_skills)

# TODO: Find the result.
print("Second highest: ", unique_skills[-2])

Second highest:  92


### Exercise 34: Combine Lists with zip

**Level:** Intermediate  
**Learning objective:** Pair corresponding values.

#### Task
Create formatted strings.

#### Expected output
```text
['Sara: 95', 'Ali: 82', 'Nora: 89']
```

<details>
<summary><strong>Hint</strong></summary>

Loop over `zip(names, scores)`.

</details>

In [56]:
names = ["Sara", "Ali", "Nora"]
scores = [95, 82, 89]

result = []

# TODO: Combine the lists.
index = 0
length = len(names)
while index < length:
    temp = names[index] + ": " + str(scores[index])
    result.append(temp)
    index += 1

print(result)

['Sara: 95', 'Ali: 82', 'Nora: 89']


### Exercise 35: Nested List Averages

**Level:** Intermediate+  
**Learning objective:** Process lists containing other lists.

#### Task
Print each student's average.

#### Expected output
```text
Sara: 90.0
Ali: 75.0
Nora: 88.0
```

<details>
<summary><strong>Hint</strong></summary>

Each record contains a name followed by scores.

</details>

In [70]:
student_records = [
    ["Sara", 90, 95, 85],
    ["Ali", 70, 75, 80],
    ["Nora", 88, 92, 84],
]

# TODO: Calculate and print averages.
for items in student_records:
    sum = 0.0
    for item in items:
        if isinstance(item, int):
           sum += item
    average = sum / (len(items) - 1)

    print(f"{items[0]}: {average}")

Sara: 90.0
Ali: 75.0
Nora: 88.0


### Exercise 36: List Comprehension

**Level:** Intermediate+  
**Learning objective:** Filter and transform in one expression.

#### Task
Create squares of even values.

#### Expected output
```text
[4, 16, 36, 64, 100]
```

<details>
<summary><strong>Hint</strong></summary>

Use a list comprehension.

</details>

In [71]:
numbers = list(range(1, 11))

# TODO: Create even_squares.
even_squares = []
for number in numbers:
    if number % 2 == 0:
        even_squares.append(number)

print(even_squares)

[2, 4, 6, 8, 10]


# 6. NumPy Arrays

A **NumPy array** is a collection designed for numerical computation.

Python lists are general-purpose collections:

```python
python_list = [1, 2, 3]
```

NumPy arrays are optimized for calculations:

```python
import numpy as np

numbers = np.array([1, 2, 3])
```

## Why Use NumPy Arrays?

- Fast numerical operations
- Vectorized calculations
- One-dimensional and multi-dimensional data
- Useful properties such as `shape`, `size`, `ndim`, and `dtype`
- Easy filtering and statistical calculations

## Important Difference Between a List and an Array

```python
python_list = [1, 2, 3]
print(python_list * 2)
```

Output:

```text
[1, 2, 3, 1, 2, 3]
```

```python
numpy_array = np.array([1, 2, 3])
print(numpy_array * 2)
```

Output:

```text
[2 4 6]
```

The list is repeated, while the NumPy array performs numerical multiplication.

## 6.1 Importing NumPy

In [2]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.5.1


## 6.2 Creating Arrays

| Function | Purpose |
|---|---|
| `np.array([...])` | Create an array from existing values |
| `np.arange(start, stop, step)` | Create values within a range |
| `np.zeros(shape)` | Create an array filled with zeros |
| `np.ones(shape)` | Create an array filled with ones |
| `np.full(shape, value)` | Create an array filled with one chosen value |
| `np.linspace(start, stop, count)` | Create evenly spaced values |

Examples:

```python
numbers = np.array([10, 20, 30])
sequence = np.arange(1, 6)
zeros = np.zeros(4)
matrix = np.ones((2, 3))
```

## Worked Example 1 — Creating and Inspecting Arrays

In [3]:
numbers = np.array([10, 20, 30, 40, 50])

print("Array:", numbers)
print("Shape:", numbers.shape)
print("Size:", numbers.size)
print("Dimensions:", numbers.ndim)
print("Data type:", numbers.dtype)

zeros = np.zeros(4)
ones_matrix = np.ones((2, 3))

print("Zeros:", zeros)
print("Ones matrix:")
print(ones_matrix)

Array: [10 20 30 40 50]
Shape: (5,)
Size: 5
Dimensions: 1
Data type: int64
Zeros: [0. 0. 0. 0.]
Ones matrix:
[[1. 1. 1.]
 [1. 1. 1.]]


## Array Properties

| Property | Meaning |
|---|---|
| `.shape` | Number of elements along each dimension |
| `.size` | Total number of elements |
| `.ndim` | Number of dimensions |
| `.dtype` | Data type of the elements |

Examples:

- Shape `(5,)` means a one-dimensional array with five values.
- Shape `(2, 3)` means two rows and three columns.

## 6.3 Indexing and Slicing

NumPy arrays use indexing and slicing similar to lists.

```python
numbers = np.array([10, 20, 30, 40, 50])

numbers[0]      # First item
numbers[-1]     # Last item
numbers[1:4]    # Items from index 1 to 3
numbers[::2]    # Every second item
```

For a two-dimensional array:

```python
matrix[row, column]
```

Examples:

```python
matrix[0, 1]     # Row 0, column 1
matrix[1, :]     # Entire second row
matrix[:, 2]     # Entire third column
matrix[:2, :2]   # Top-left 2 × 2 section
```

## Worked Example 2 — Indexing and Slicing

In [7]:
numbers = np.array([10, 20, 30, 40, 50, 60])

print("First:", numbers[0])
print("Last:", numbers[-1])
print("Middle section:", numbers[1:5])
print("Every second:", numbers[::2])

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

print("Second row:", matrix[1, :])
print("Third column:", matrix[:, 2])
print("Top-left section:")
print(matrix[:2, :2])

First: 10
Last: 60
Middle section: [20 30 40 50]
Every second: [10 30 50]
Second row: [4 5 6]
Third column: [3 6 9]
Top-left section:
[[1 2]
 [4 5]]


## 6.4 Vectorized Operations

A vectorized operation is applied to every element without writing an explicit loop.

```python
values = np.array([10, 20, 30])

values + 5
values * 2
values ** 2
```

Arrays can also be combined element by element:

```python
first = np.array([1, 2, 3])
second = np.array([10, 20, 30])

first + second
```

Result:

```text
[11 22 33]
```

## Worked Example 3 — Vectorized Arithmetic

In [8]:
scores = np.array([70, 80, 90, 100])

increased_scores = scores + 5
percentages = scores / 100
squared_scores = scores ** 2

print("Original:", scores)
print("After adding 5:", increased_scores)
print("Percentages:", percentages)
print("Squared:", squared_scores)

Original: [ 70  80  90 100]
After adding 5: [ 75  85  95 105]
Percentages: [0.7 0.8 0.9 1. ]
Squared: [ 4900  6400  8100 10000]


## 6.5 Statistical Operations

| Method | Purpose |
|---|---|
| `.sum()` | Total |
| `.mean()` | Average |
| `.min()` | Minimum |
| `.max()` | Maximum |
| `.std()` | Standard deviation |
| `.argmin()` | Index of minimum |
| `.argmax()` | Index of maximum |

For two-dimensional arrays, use `axis`:

- `axis=0`: calculate down the rows, producing one result per column.
- `axis=1`: calculate across the columns, producing one result per row.

## Worked Example 4 — Array Statistics and Axes

In [9]:
scores = np.array([
    [70, 80, 90],
    [85, 90, 95],
    [60, 70, 80],
])

print("Overall mean:", scores.mean())
print("Highest score:", scores.max())
print("Row averages:", scores.mean(axis=1))
print("Column averages:", scores.mean(axis=0))
print("Top score position:", np.unravel_index(scores.argmax(), scores.shape))

Overall mean: 80.0
Highest score: 95
Row averages: [80. 90. 70.]
Column averages: [71.66666667 80.         88.33333333]
Top score position: (np.int64(1), np.int64(2))


## 6.6 Boolean Filtering

A condition applied to an array produces a Boolean array.

```python
scores = np.array([55, 72, 91, 85])

scores >= 80
```

Result:

```text
[False False  True  True]
```

Use the Boolean array to select matching values:

```python
scores[scores >= 80]
```

Multiple conditions require parentheses and `&` or `|`:

```python
scores[(scores >= 70) & (scores < 90)]
```

## Worked Example 5 — Filtering and Conditional Replacement

In [ ]:
scores = np.array([55, 72, 91, 85, 60, 88, 95, 79])

high_scores = scores[scores >= 85]
middle_range = scores[(scores >= 70) & (scores < 90)]
adjusted_scores = np.where(scores < 60, 60, scores)

print("Scores >= 85:", high_scores)
print("Scores from 70 to 89:", middle_range)
print("Adjusted scores:", adjusted_scores)

## 6.7 Reshaping Arrays

`reshape()` changes the dimensions without changing the values.

```python
numbers = np.arange(1, 13)
matrix = numbers.reshape(3, 4)
```

The total number of values must remain the same.

Twelve values can be reshaped into:

- `(3, 4)`
- `(4, 3)`
- `(2, 6)`
- `(6, 2)`

but not `(5, 3)`.

## Worked Example 6 — Reshape and Flatten

In [10]:
numbers = np.arange(1, 13)

matrix = numbers.reshape(3, 4)
flattened = matrix.flatten()

print("Original:")
print(numbers)

print("Matrix:")
print(matrix)

print("Flattened:")
print(flattened)

Original:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened:
[ 1  2  3  4  5  6  7  8  9 10 11 12]


## Common Mistakes

### Mistake 1 — Forgetting to Import NumPy

```python
numbers = np.array([1, 2, 3])
```

requires:

```python
import numpy as np
```

### Mistake 2 — Expecting List Behavior

```python
[1, 2, 3] * 2
```

repeats the list, while:

```python
np.array([1, 2, 3]) * 2
```

multiplies the values.

### Mistake 3 — Using `and` with Array Conditions

Incorrect:

```python
scores[(scores >= 70) and (scores < 90)]
```

Correct:

```python
scores[(scores >= 70) & (scores < 90)]
```

### Mistake 4 — Reshaping to an Invalid Size

The number of rows multiplied by columns must equal the number of elements.

### Mistake 5 — Confusing `axis=0` and `axis=1`

- `axis=0` returns one result per column.
- `axis=1` returns one result per row.

## Exercises — NumPy Arrays

### Exercise 37: Create and Inspect an Array

**Level:** Basic  
**Learning objective:** Create a one-dimensional array and inspect its properties.

#### Task
Create the array and print its shape, size, and number of dimensions.

#### Expected output
```text
Array: [ 5 10 15 20 25]
Shape: (5,)
Size: 5
Dimensions: 1
```

<details>
<summary><strong>Hint</strong></summary>

Use `np.array()` and the properties `.shape`, `.size`, and `.ndim`.

</details>

In [11]:
import numpy as np
numbers = None

# TODO: Create the array.
numbers = np.array([5, 10, 15, 20, 25])

print("Array:", numbers)
print("Shape:", numbers.shape)
print("Size:", numbers.size)
print("Dimensions:", numbers.ndim)

Array: [ 5 10 15 20 25]
Shape: (5,)
Size: 5
Dimensions: 1


### Exercise 38: Array Indexing and Slicing

**Level:** Basic  
**Learning objective:** Access elements and slices.

#### Task
Print the second item, last item, first four items, and every second item.

#### Expected output
```text
Second: 20
Last: 60
First four: [10 20 30 40]
Every second: [10 30 50]
```

<details>
<summary><strong>Hint</strong></summary>

Use indexing and slicing just as you would with a list.

</details>

In [14]:
numbers = np.array([10, 20, 30, 40, 50, 60])

# TODO: Print the requested values.
print(numbers[1])
print(numbers[-1])
print(numbers[0:4])
print(numbers[::2])

20
60
[10 20 30 40]
[10 30 50]


### Exercise 39: Vectorized Arithmetic

**Level:** Basic  
**Learning objective:** Perform calculations on every array element.

#### Task
Multiply each value by 3, then subtract 5.

#### Expected output
```text
Original: [ 5 10 15 20]
Result: [10 25 40 55]
```

<details>
<summary><strong>Hint</strong></summary>

Use one expression: `(values * 3) - 5`.

</details>

In [16]:
values = np.array([5, 10, 15, 20])

# TODO: Calculate the result.
result = values * 3
result = result - 5

print("Original:", values)
print("Result:", result)

Original: [ 5 10 15 20]
Result: [10 25 40 55]


### Exercise 40: Array Statistics

**Level:** Basic  
**Learning objective:** Use NumPy statistical methods.

#### Task
Print minimum, maximum, sum, mean, and standard deviation rounded to two decimals.

#### Expected output
```text
Minimum: 60
Maximum: 100
Sum: 400
Mean: 80.0
Standard deviation: 14.14
```

<details>
<summary><strong>Hint</strong></summary>

Use `.min()`, `.max()`, `.sum()`, `.mean()`, and `.std()`.

</details>

In [21]:
scores = np.array([60, 70, 80, 90, 100])

# TODO: Calculate and print the statistics.
print("Minimum:", scores.min())
print("Maximum:", scores.max())
print("Sum:", scores.sum())
print("Mean:", scores.mean())
print(f"Standard deviation: {scores.std():.2f}")

Minimum: 60
Maximum: 100
Sum: 400
Mean: 80.0
Standard deviation: 14.14


### Exercise 41: Boolean Filtering

**Level:** Intermediate  
**Learning objective:** Filter array values using two conditions.

#### Task
Select scores from 70 through 89 inclusive.

#### Expected output
```text
[72 85 88 79]
```

<details>
<summary><strong>Hint</strong></summary>

Use `(scores >= 70) & (scores <= 89)`.

</details>

In [23]:
scores = np.array([55, 72, 91, 85, 60, 88, 95, 79])

# TODO: Apply Boolean filtering.
filtered_scores = scores[(scores >= 70) & (scores <= 89)]

print(filtered_scores)

[72 85 88 79]


### Exercise 42: Conditional Replacement with np.where

**Level:** Intermediate  
**Learning objective:** Replace values based on a condition.

#### Task
Replace every score below 60 with 60.

#### Expected output
```text
[60 60 74 88 60 95]
```

<details>
<summary><strong>Hint</strong></summary>

Use `np.where(condition, replacement, original_array)`.

</details>

In [24]:
scores = np.array([45, 58, 74, 88, 52, 95])

# TODO: Replace low scores.
adjusted_scores = np.where(scores < 60, 60, scores)

print(adjusted_scores)

[60 60 74 88 60 95]


### Exercise 43: Reshape an Array

**Level:** Intermediate  
**Learning objective:** Convert a one-dimensional array into a matrix.

#### Task
Create numbers 1 through 12 and reshape them into 3 rows and 4 columns.

#### Expected output
```text
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
```

<details>
<summary><strong>Hint</strong></summary>

Use `np.arange(1, 13).reshape(3, 4)`.

</details>

In [25]:
# TODO: Create and reshape the array.
matrix = np.reshape(np.arange(1, 13), (3, 4))

print(matrix)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Exercise 44: Matrix Row and Column Selection

**Level:** Intermediate  
**Learning objective:** Select rows, columns, and sections from a matrix.

#### Task
Print the second row, third column, and top-left 2 × 2 section.

#### Expected output
```text
Second row: [4 5 6]
Third column: [3 6 9]
Top-left section:
[[1 2]
 [4 5]]
```

<details>
<summary><strong>Hint</strong></summary>

Use `matrix[row_selection, column_selection]`.

</details>

In [27]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

# TODO: Print the requested sections.
print("Second row", matrix[1, :])
print("Third column", matrix[:, 2])
print("Top-left section:\n", matrix[:2, :2])

Second row [4 5 6]
Third column [3 6 9]
Top-left section:
 [[1 2]
 [4 5]]


### Exercise 45: Row and Column Averages

**Level:** Intermediate+  
**Learning objective:** Use the `axis` parameter.

#### Task
Calculate averages for each row and each column.

#### Expected output
```text
Row averages: [80. 90. 70.]
Column averages: [71.67 80.   88.33]
```

<details>
<summary><strong>Hint</strong></summary>

`axis=1` gives row averages; `axis=0` gives column averages.

</details>

In [29]:
scores = np.array([
    [70, 80, 90],
    [85, 90, 95],
    [60, 70, 80],
])

# TODO: Calculate row and column averages.
row_averages = scores.mean(axis=1)
column_averages = scores.mean(axis=0)

print("Row averages:", row_averages)
print("Column averages:", column_averages)

Row averages: [80. 90. 70.]
Column averages: [71.66666667 80.         88.33333333]


### Exercise 46: Min-Max Normalization

**Level:** Intermediate+  
**Learning objective:** Scale values into the range 0 to 1.

#### Task
Normalize the array using min-max normalization.

#### Expected output
```text
[0.   0.25 0.5  0.75 1.  ]
```

<details>
<summary><strong>Hint</strong></summary>

Use `(values - values.min()) / (values.max() - values.min())`.

</details>

In [30]:
values = np.array(
    [10, 20, 30, 40, 50],
    dtype=float,
)

# TODO: Normalize the values.
normalized = (values - values.min()) / (values.max() - values.min())

print(normalized)

[0.   0.25 0.5  0.75 1.  ]


## Mini Challenge — Student Score Matrix

Rows represent students and columns represent assignments.

```python
students = ["Sara", "Ali", "Nora"]

scores = np.array([
    [90, 85, 95],
    [70, 75, 80],
    [88, 92, 84],
])
```

Required:

1. Calculate each student's average.
2. Find the highest score in the matrix.
3. Identify the student with the highest average.
4. Select all scores greater than or equal to 90.

Expected summary:

```text
Sara: 90.0
Ali: 75.0
Nora: 88.0
Highest score: 95
Top student: Sara
Scores >= 90: [90 95 92]
```

In [45]:
students = ["Sara", "Ali", "Nora"]

scores = np.array([
    [90, 85, 95],
    [70, 75, 80],
    [88, 92, 84],
])

# exploring
"""
print(scores)
print(scores[0])
print(scores[0].sum())
"""

# TODO:
# 1. Calculate each student's average.
index = 0
length = len(students)
students_ranked = {}
while index < length:
    current_avg = scores[index].mean()
    students_ranked[students[index]] = current_avg
    print(f"{students[index]}: {current_avg}")
    index += 1
#print(students_ranked)

# 2. Find the highest score.
print(f"Highest score: {scores.max()}")

# 3. Identify the top student.
# print(sorted(students_ranked, reverse=True))
print("Top student:", next(iter(sorted(students_ranked, reverse=True))))

# 4. Select scores greater than or equal to 90.
high_scores = scores[(scores >= 90)]
print("Scores >= 90:", high_scores)

# 5. Print the complete summary.

Sara: 90.0
Ali: 75.0
Nora: 88.0
Highest score: 95
Top student: Sara
Scores >= 90: [90 95 92]


# 7. Tuples and Sets

Tuples and sets are both Python collection types, but they solve different problems.

## Quick Comparison

| Feature | Tuple | Set |
|---|---|---|
| Syntax | `(1, 2, 3)` | `{1, 2, 3}` |
| Ordered | Yes | No guaranteed display order |
| Duplicates | Allowed | Removed automatically |
| Mutable | No | Yes |
| Indexing | Supported | Not supported |
| Main use | Fixed ordered records | Unique values and set operations |

---

# 6.1 Tuples

A **tuple** is an ordered, immutable collection.

```python
coordinates = (24.7136, 46.6753)
```

Tuples are appropriate when:

- values belong together,
- order matters,
- the record should not change,
- a function returns multiple values.

## Creating Tuples

```python
empty_tuple = ()
numbers = (10, 20, 30)
mixed = ("Maha", 22, True)
```

### Single-Item Tuple

A comma is required:

```python
single_value = (95,)
```

Without the comma:

```python
single_value = (95)
```

Python treats it as an integer, not a tuple.

## Worked Example 1 — Creating, Indexing, and Slicing Tuples

In [ ]:
courses = ("Python", "SQL", "Git", "Cloud")

print("Tuple:", courses)
print("Type:", type(courses))
print("First item:", courses[0])
print("Last item:", courses[-1])
print("First two:", courses[:2])
print("Reversed:", courses[::-1])
print("Length:", len(courses))

## Tuple Operations and Methods

| Operation | Example |
|---|---|
| Indexing | `values[0]` |
| Negative indexing | `values[-1]` |
| Slicing | `values[1:3]` |
| Membership | `"Python" in courses` |
| Length | `len(values)` |
| Count value | `values.count(4)` |
| Find index | `values.index(7)` |
| Concatenate | `(1, 2) + (3, 4)` |
| Repeat | `("A",) * 3` |

Tuples have fewer methods than lists because tuples cannot be modified.

## Worked Example 2 — Tuple Methods and Operators

In [ ]:
values = (4, 2, 4, 7, 4, 9)

print("Count of 4:", values.count(4))
print("Index of 7:", values.index(7))
print("Contains 9:", 9 in values)
print("Combined:", values + (10, 11))
print("Repeated:", ("AI",) * 3)

## Tuple Unpacking

Tuple unpacking assigns tuple elements to separate variables.

```python
student = ("Sara", 95)
name, score = student
```

The number of variables must normally match the number of tuple elements.

### Starred Unpacking

A starred variable collects remaining values into a list:

```python
record = ("Maha", 85, 90, 95)
name, *scores = record
```

## Worked Example 3 — Normal and Starred Unpacking

In [ ]:
location = (24.7136, 46.6753)
latitude, longitude = location

print("Latitude:", latitude)
print("Longitude:", longitude)

student_record = ("Maha", 85, 90, 95)
student_name, *student_scores = student_record

print("Student:", student_name)
print("Scores:", student_scores)
print("Average:", sum(student_scores) / len(student_scores))

## Tuple Immutability

Tuple elements cannot be replaced directly.

```python
courses = ("Python", "SQL")
courses[0] = "Java"
```

This raises `TypeError`.

When a change is genuinely required, convert to a list, modify it, then convert back:

```python
courses_list = list(courses)
courses_list.append("Git")
courses = tuple(courses_list)
```

Immutability helps protect fixed records from accidental modification.

## Worked Example 4 — Converting Between Tuple and List

In [ ]:
original_tuple = ("Python", "SQL")

temporary_list = list(original_tuple)
temporary_list.append("Git")

updated_tuple = tuple(temporary_list)

print("Original tuple:", original_tuple)
print("Updated tuple:", updated_tuple)

---

# 6.2 Sets

A **set** is a mutable collection of unique values.

```python
skills = {"Python", "SQL", "Git"}
```

Sets are useful for:

- removing duplicates,
- fast membership checks,
- comparing groups,
- finding shared or different values.

## Creating Sets

```python
skills = {"Python", "SQL"}
numbers = set([1, 2, 2, 3])
```

### Empty Set

Correct:

```python
empty_set = set()
```

Incorrect:

```python
empty_set = {}
```

`{}` creates an empty dictionary, not a set.

## Worked Example 5 — Uniqueness and Membership

In [ ]:
skills_list = ["Python", "SQL", "Python", "Git", "SQL"]

unique_skills = set(skills_list)

print("Original list:", skills_list)
print("Unique skills:", sorted(unique_skills))
print("Contains Python:", "Python" in unique_skills)
print("Contains Java:", "Java" in unique_skills)

## Adding and Removing Set Elements

| Method | Purpose |
|---|---|
| `.add(value)` | Add one value |
| `.update(iterable)` | Add multiple values |
| `.remove(value)` | Remove value; raises `KeyError` if absent |
| `.discard(value)` | Remove value safely if present |
| `.pop()` | Remove an arbitrary element |
| `.clear()` | Remove all elements |

Use `discard()` when the value may not exist.

## Worked Example 6 — Updating a Set

In [ ]:
skills = {"Python", "SQL"}

skills.add("Git")
skills.update({"Cloud", "AI"})
skills.discard("SQL")
skills.discard("Java")  # No error when absent

print("Updated skills:", sorted(skills))

## Mathematical Set Operations

Assume:

```python
a = {"Ali", "Sara", "Nora"}
b = {"Sara", "Nora", "Omar"}
```

| Operation | Operator | Meaning |
|---|---|---|
| Union | `a | b` | All values from both sets |
| Intersection | `a & b` | Values shared by both |
| Difference | `a - b` | Values in `a` but not `b` |
| Symmetric difference | `a ^ b` | Values in exactly one set |

Equivalent methods include:

```python
a.union(b)
a.intersection(b)
a.difference(b)
a.symmetric_difference(b)
```

## Worked Example 7 — Comparing Two Groups

In [ ]:
registered = {"Ali", "Sara", "Nora"}
attended = {"Sara", "Nora", "Omar"}

both = registered & attended
registered_but_absent = registered - attended
new_attendees = attended - registered
all_students = registered | attended
exactly_one_group = registered ^ attended

print("Registered and attended:", sorted(both))
print("Registered but absent:", sorted(registered_but_absent))
print("Attended but not registered:", sorted(new_attendees))
print("All students:", sorted(all_students))
print("Exactly one group:", sorted(exactly_one_group))

## Set Relationships

| Method | Question answered |
|---|---|
| `a.issubset(b)` | Are all values of `a` inside `b`? |
| `a.issuperset(b)` | Does `a` contain all values of `b`? |
| `a.isdisjoint(b)` | Do the sets have no shared values? |

The operators `<`, `<=`, `>`, and `>=` can also express subset and superset relationships.

## Worked Example 8 — Subset, Superset, and Disjoint

In [ ]:
required_skills = {"Python", "SQL"}
candidate_skills = {"Python", "SQL", "Git", "Statistics"}
design_skills = {"Figma", "Illustrator"}

print(
    "Required is subset:",
    required_skills.issubset(candidate_skills),
)
print(
    "Candidate is superset:",
    candidate_skills.issuperset(required_skills),
)
print(
    "Technical and design are disjoint:",
    candidate_skills.isdisjoint(design_skills),
)

## Sets Do Not Support Indexing

This is invalid:

```python
skills = {"Python", "SQL"}
skills[0]
```

A set is not accessed by position.

To display a stable order for teaching or reports:

```python
sorted(skills)
```

`sorted()` returns a list.

## Common Mistakes

### Mistake 1 — Creating an Empty Dictionary Instead of a Set

```python
values = {}
```

Correct:

```python
values = set()
```

### Mistake 2 — Expecting Duplicates

```python
{1, 1, 2, 2}
```

becomes:

```python
{1, 2}
```

### Mistake 3 — Using `remove()` for an Optional Value

```python
skills.remove("Java")
```

raises `KeyError` when `"Java"` is absent.

Use:

```python
skills.discard("Java")
```

### Mistake 4 — Expecting Set Output Order

Set order should not be used as part of program logic. Use `sorted()` when consistent display order is needed.

## Exercises — Tuples and Sets

### Exercise 47: Tuple Access

**Level:** Basic  
**Learning objective:** Access values from a tuple.

#### Task
Print latitude and longitude.

#### Expected output
```text
Latitude: 24.7136
Longitude: 46.6753
```

<details>
<summary><strong>Hint</strong></summary>

Use unpacking.

</details>

In [72]:
location = (24.7136, 46.6753)

# TODO: Unpack and print.
print("Latitude:", location[0])
print("Longitude:", location[1])

Latitude: 24.7136
Longitude: 46.6753


### Exercise 48: Single-Item Tuple

**Level:** Basic  
**Learning objective:** Understand tuple syntax.

#### Task
Create a one-item tuple and print its type.

#### Expected output
```text
(95,)
<class 'tuple'>
```

<details>
<summary><strong>Hint</strong></summary>

Include a comma after the value.

</details>

In [73]:
# TODO: Create a single-item tuple.
single_item_tup = (95,)

# TODO: Print value and type.
print(single_item_tup)
print(type(single_item_tup))

(95,)
<class 'tuple'>


### Exercise 49: Tuple Statistics

**Level:** Intermediate  
**Learning objective:** Use tuple methods.

#### Task
Print count of 4 and index of 7.

#### Expected output
```text
Count of 4: 3
Index of 7: 3
```

<details>
<summary><strong>Hint</strong></summary>

Use `.count()` and `.index()`.

</details>

In [75]:
values = (4, 2, 4, 7, 4, 9)

# TODO: Print both results.
print("Count of 4: ", values.count(4))
print("Index of 7: ", values.index(7))

Count of 4:  3
Index of 7:  3


### Exercise 50: Remove Duplicates with a Set

**Level:** Basic  
**Learning objective:** Convert a list into unique values.

#### Task
Print sorted unique values.

#### Expected output
```text
[1, 2, 3, 4, 5]
```

<details>
<summary><strong>Hint</strong></summary>

Use `set()` and `sorted()`.

</details>

In [76]:
values = [1, 2, 2, 3, 4, 4, 5]
unique_values = list(set(values))

# TODO: Create sorted unique values.
print(unique_values)

[1, 2, 3, 4, 5]


### Exercise 51: Set Intersection and Difference

**Level:** Intermediate  
**Learning objective:** Compare two groups.

#### Task
Print shared, only first, and only second.

#### Expected output
```text
Shared: ['Nora', 'Sara']
Only first: ['Ali']
Only second: ['Omar']
```

<details>
<summary><strong>Hint</strong></summary>

Use `&` and directional differences.

</details>

In [77]:
first_group = {"Ali", "Sara", "Nora"}
second_group = {"Sara", "Nora", "Omar"}

# TODO: Calculate and print sorted results.
shared = []
only_first = []
only_second = []

for item in first_group:
    if item in second_group:
        shared.append(item)
    else:
        only_first.append(item)

for item in second_group:
    if item not in shared and item not in first_group:
        only_second.append(item)

print("Shared: ", shared)
print("Only first: ", only_first)
print("Only second: ", only_second)

Shared:  ['Nora', 'Sara']
Only first:  ['Ali']
Only second:  ['Omar']


### Exercise 52: Symmetric Difference

**Level:** Intermediate  
**Learning objective:** Find values in exactly one set.

#### Task
Print sorted values.

#### Expected output
```text
['Ali', 'Lama', 'Nora', 'Omar']
```

<details>
<summary><strong>Hint</strong></summary>

Use `^` and `sorted()`.

</details>

In [79]:
workshop_a = {"Ali", "Sara", "Nora"}
workshop_b = {"Sara", "Omar", "Lama"}

# TODO: Calculate and print.
unique_values = []
for item in workshop_a:
    if item not in workshop_b:
        unique_values.append(item)

for item in workshop_b:
    if item not in workshop_a:
        unique_values.append(item)

unique_values.sort()
print(unique_values)

['Ali', 'Lama', 'Nora', 'Omar']


### Exercise 53: Subset and Superset

**Level:** Intermediate  
**Learning objective:** Check set relationships.

#### Task
Print both Boolean results.

#### Expected output
```text
Required is subset: True
Candidate is superset: True
```

<details>
<summary><strong>Hint</strong></summary>

Use `.issubset()` and `.issuperset()`.

</details>

In [80]:
required = {"Python", "SQL"}
candidate = {"Python", "SQL", "Git", "Statistics"}

# TODO: Print the two checks.
print("Required is subset:", required.issubset(candidate))
print("Candidate is superset", candidate.issuperset(required))

Required is subset: True
Candidate is superset True


### Exercise 54: Set Updates

**Level:** Intermediate  
**Learning objective:** Use add, discard, and update.

#### Task
Start with Python and SQL, add Git, remove SQL safely, and add Cloud and AI.

#### Expected output
```text
['AI', 'Cloud', 'Git', 'Python']
```

<details>
<summary><strong>Hint</strong></summary>

Use `add()`, `discard()`, and `update()`.

</details>

In [81]:
skills = {"Python", "SQL"}

# TODO: Update the set.
skills.add("Git")
skills.remove("SQL")
skills.add("Cloud")
skills.add("AI")

print(sorted(skills))

['AI', 'Cloud', 'Git', 'Python']


# 8. Dictionaries

A **dictionary** stores key-value pairs.

```python
student = {
    "name": "Maha",
    "score": 92,
}
```

Dictionary characteristics:
- keys are unique,
- values may repeat,
- values are accessed using keys,
- dictionaries are mutable.

## Dictionary Operations

| Operation | Example |
|---|---|
| Create | `student = {"name": "Maha"}` |
| Access | `student["name"]` |
| Safe access | `student.get("email", "Not found")` |
| Add/update | `student["level"] = 4` |
| Remove | `student.pop("score")` |
| Keys | `student.keys()` |
| Values | `student.values()` |
| Pairs | `student.items()` |
| Update many | `student.update({...})` |
| Clear | `student.clear()` |
| Set default | `student.setdefault("level", 1)` |

double check safe get

## Worked Example 1 — Create and Update

In [ ]:
student = {
    "name": "Maha",
    "major": "Artificial Intelligence",
    "score": 92,
}

print("Name:", student["name"])

student["score"] = 95
student["level"] = 4

print("Updated:", student)

## Worked Example 2 — Loop Through Items

In [ ]:
prices = {
    "Keyboard": 180,
    "Mouse": 90,
    "Monitor": 950,
}

total = 0

for product, price in prices.items():
    print(f"{product}: {price} SAR")
    total += price

print("Total:", total, "SAR")

## Worked Example 3 — Nested Dictionary

In [ ]:
student = {
    "name": "Sara",
    "academic": {
        "major": "Data Science",
        "scores": [90, 95, 88],
    },
}

major = student["academic"]["major"]
scores = student["academic"]["scores"]
average = sum(scores) / len(scores)

print("Major:", major)
print("Average:", round(average, 2))

## Common Mistake: Missing Key

This raises `KeyError`:

```python
student["email"]
```

Safer:

```python
student.get("email", "Email not available")
```

## Exercises — Dictionaries

### Exercise 55: Access Dictionary Values

**Level:** Basic  
**Learning objective:** Retrieve values by key.

#### Task
Print employee details.

#### Expected output
```text
Name: Sara
Department: Data
Salary: 15000
```

<details>
<summary><strong>Hint</strong></summary>

Use square brackets with key names.

</details>

In [83]:
employee = {
    "name": "Sara",
    "department": "Data",
    "salary": 15000,
}

# TODO: Print the values.
for key, value in employee.items():
    print(f"{key}: {value}")

name: Sara
department: Data
salary: 15000


### Exercise 56: Add and Update Keys

**Level:** Basic  
**Learning objective:** Modify a dictionary.

#### Task
Add level and update score.

#### Expected output
```text
{'name': 'Nora', 'score': 96, 'level': 4}
```

<details>
<summary><strong>Hint</strong></summary>

Assign new values using keys.

</details>

In [84]:
student = {
    "name": "Nora",
    "score": 89,
}

# TODO: Add and update.
student["level"] = 4

print(student)

{'name': 'Nora', 'score': 89, 'level': 4}


### Exercise 57: Safe Access

**Level:** Basic  
**Learning objective:** Use `.get()` for optional data.

#### Task
Print default text when email is missing.

#### Expected output
```text
Email not available
```

<details>
<summary><strong>Hint</strong></summary>

Use `student.get('email', 'Email not available')`.

</details>

In [85]:
student = {
    "name": "Ali",
    "score": 82,
}

# TODO: Print the email safely.
print(student.get("email", "Email not available"))

Email not available


### Exercise 58: Loop Through Items

**Level:** Basic  
**Learning objective:** Use `.items()`.

#### Task
Print each product and price.

#### Expected output
```text
Keyboard: 180 SAR
Mouse: 90 SAR
Monitor: 950 SAR
```

<details>
<summary><strong>Hint</strong></summary>

Unpack each pair.

</details>

In [86]:
prices = {
    "Keyboard": 180,
    "Mouse": 90,
    "Monitor": 950,
}

# TODO: Loop and print.
for key, value in prices.items():
    print(f"{key}: {value} SAR")

Keyboard: 180 SAR
Mouse: 90 SAR
Monitor: 950 SAR


### Exercise 59: Dictionary Statistics

**Level:** Intermediate  
**Learning objective:** Aggregate numeric values.

#### Task
Print total, highest, lowest, and average.

#### Expected output
```text
Total: 340
Highest: 95
Lowest: 75
Average: 85.0
```

<details>
<summary><strong>Hint</strong></summary>

Use `scores.values()`.

</details>

In [87]:
scores = {
    "Sara": 95,
    "Ali": 75,
    "Nora": 88,
    "Omar": 82,
}

# TODO: Calculate statistics.
length = len(scores)
total = 0
highest = 0
lowest = 999
average = 0.0

for key, value in scores.items():
    if value > highest:
        highest = value
    if value < lowest:
        lowest = value
    total += value
average = float(total) / length

print("Total: ", total)
print("Highest:", highest)
print("Lowest:", lowest)
print("Average:", average)

Total:  340
Highest: 95
Lowest: 75
Average: 85.0


### Exercise 60: Filter a Dictionary

**Level:** Intermediate  
**Learning objective:** Create a dictionary containing matching records.

#### Task
Keep scores at least 85.

#### Expected output
```text
{'Sara': 95, 'Nora': 88}
```

<details>
<summary><strong>Hint</strong></summary>

Use a loop or dictionary comprehension.

</details>

In [88]:
scores = {
    "Sara": 95,
    "Ali": 75,
    "Nora": 88,
    "Omar": 82,
}

high_scores = {}

# TODO: Filter the dictionary.
for key, value in scores.items():
    if value >= 85:
        high_scores[key] = value

print(high_scores)

{'Sara': 95, 'Nora': 88}


### Exercise 61: Word Frequency

**Level:** Intermediate  
**Learning objective:** Use a dictionary as a counter.

#### Task
Count each word.

#### Expected output
```text
{'python': 2, 'is': 2, 'simple': 1, 'and': 1, 'powerful': 1}
```

<details>
<summary><strong>Hint</strong></summary>

Use `.get(word, 0) + 1`.

</details>

In [91]:
sentence = "python is simple and python is powerful"
word_counts = {}

# TODO: Count words.
for word in sentence.split():
    word_counts[word] = word_counts.get(word, 0) + 1

print(word_counts)

{'python': 2, 'is': 2, 'simple': 1, 'and': 1, 'powerful': 1}


### Exercise 62: Merge Numeric Dictionaries

**Level:** Intermediate  
**Learning objective:** Combine dictionaries and add shared values.

#### Task
Create the merged result.

#### Expected output
```text
{'A': 12, 'B': 15, 'C': 15}
```

<details>
<summary><strong>Hint</strong></summary>

Start with a copy and use `.get()`.

</details>

In [92]:
first = {"A": 12, "B": 8}
second = {"B": 7, "C": 15}

merged = {}

# TODO: Merge with addition.
for key, value in first.items():
    if key in second:
        merged[key] = first[key] + second[key]
    else:
        merged[key] = first[key]

for key, value in second.items():
    if key not in merged:
        merged[key] = value

print(merged)

{'A': 12, 'B': 15, 'C': 15}


### Exercise 63: Nested Dictionary Analysis

**Level:** Intermediate+  
**Learning objective:** Access nested values and calculate an average.

#### Task
Print major, second score, and average.

#### Expected output
```text
Major: AI
Second score: 90
Average: 90.0
```

<details>
<summary><strong>Hint</strong></summary>

Access nested structures step by step.

</details>

In [96]:
student = {
    "name": "Maha",
    "academic": {
        "major": "AI",
        "scores": [85, 90, 95],
    },
}

# TODO: Access and calculate.
print("Major: ", student["academic"]["major"])
print("Second score: ", student["academic"]["scores"][1])
average = (student["academic"]["scores"][0] + student["academic"]["scores"][1] + student["academic"]["scores"][2]) / float(3)
print("Average: ", average)

Major:  AI
Second score:  90
Average:  90.0


### Exercise 64: Group Items by Category

**Level:** Intermediate+  
**Learning objective:** Create lists inside dictionary values.

#### Task
Group products by category.

#### Expected output
```text
{'Electronics': ['Keyboard', 'Mouse'], 'Furniture': ['Desk', 'Chair']}
```

<details>
<summary><strong>Hint</strong></summary>

Use `.setdefault(category, []).append(product)`.

</details>

In [99]:
products = [
    ("Keyboard", "Electronics"),
    ("Desk", "Furniture"),
    ("Mouse", "Electronics"),
    ("Chair", "Furniture"),
]

grouped = {}

# TODO: Build the grouped dictionary.
electronics = []
furniture = []
for key, value in products:
    if value == "Electronics":
        electronics.append(key)
    elif value == "Furniture":
        furniture.append(key)

grouped = {"Electronics": electronics,
                "Furniture": furniture}

print(grouped)

{'Electronics': ['Keyboard', 'Mouse'], 'Furniture': ['Desk', 'Chair']}


# Final Integrated Challenge — Student Course Report

Use variables, strings, lists, tuples, sets, and dictionaries together.

## Given Data

In [1]:
students = {
    "Sara": {
        "major": "AI",
        "scores": [90, 95, 88],
        "skills": {"Python", "SQL"},
    },
    "Ali": {
        "major": "CS",
        "scores": [70, 75, 80],
        "skills": {"Python", "Git"},
    },
    "Nora": {
        "major": "Data Science",
        "scores": [85, 92, 89],
        "skills": {"Python", "SQL", "Statistics"},
    },
}

## Required Tasks

1. Calculate each student's average.
2. Print one formatted report line per student.
3. Create a dictionary mapping names to averages.
4. Find the student with the highest average.
5. Create a list of students whose average is at least 85.
6. Find skills shared by all students.
7. Find all unique skills.
8. Store the top student's name and average in a tuple.

## Expected Summary Format

```text
Sara | AI | Average: 91.00
Ali | CS | Average: 75.00
Nora | Data Science | Average: 88.67

Top student: Sara
High-performing students: ['Sara', 'Nora']
Shared skills: ['Python']
All skills: ['Git', 'Python', 'SQL', 'Statistics']
Top record: ('Sara', 91.0)
```

In [ ]:
students = {
    "Sara": {
        "major": "AI",
        "scores": [90, 95, 88],
        "skills": {"Python", "SQL"},
    },
    "Ali": {
        "major": "CS",
        "scores": [70, 75, 80],
        "skills": {"Python", "Git"},
    },
    "Nora": {
        "major": "Data Science",
        "scores": [85, 92, 89],
        "skills": {"Python", "SQL", "Statistics"},
    },
}

In [48]:
# TODO: Write the complete solution here.
# 1- each students avg  + dict of names --> avgs
students_dict = {}
for key, value in students.items():
    # calculating avg for each student
    temp_avg = sum(value["scores"]) / len(value["scores"])
    students_dict[key] = temp_avg

# 2- formatted report (name | major | avg)
for key, value in students_dict.items():
    print(f"{key} | {students[key]["major"]} | Average: {value:.2f}")

# 3- get highest avg
highest_avg = sorted(students_dict, reverse=True)[0]
print("\nTop student:", highest_avg)

# 4- get/create list of students w avg >= 85
high_performing = []
for key, value in students_dict.items():
    if value >= 85:
        high_performing.append(key)

print("High-performing students:", high_performing)

# 5- find skills shared by all students + find (all) unique skills
skills_frequency = {}
# getting stuff
for key, value in students.items():
    temp_list_skills = value["skills"]
    for skill in temp_list_skills:
        skills_frequency[skill] = skills_frequency.get(skill, 0) + 1

# printing stuff
shared_skills = []
length = len(students)
for key, value in skills_frequency.items():
    if value == length:
        shared_skills.append(key)

all_skills = list(skills_frequency)
print("Shared skills:", shared_skills)
print("All skills:", all_skills)

# 6- store top student's name and avg in tuple
top_student_tup = (highest_avg, students_dict[highest_avg])
print("Top record:", top_student_tup)

Sara | AI | Average: 91.00
Ali | CS | Average: 75.00
Nora | Data Science | Average: 88.67

Top student: Sara
High-performing students: ['Sara', 'Nora']
Shared skills: ['Python']
All skills: ['Python', 'SQL', 'Git', 'Statistics']
Top record: ('Sara', 91.0)


# Final Reflection

Answer briefly:

1. Which topic required the most debugging?
- the numpy one
2. What is the main difference between a list and a tuple?
- lists allow modifications (mutable), while tupes do not (immutable)
3. When is a set more appropriate than a list?
- when we only care about unique values
4. Why is `.get()` sometimes safer than square-bracket dictionary access?
- because if the value doesn't exist, it returns either None or sets a new value for it
5. Choose one exercise with a loop and state its approximate time complexity.
- i feel like they all took around the same amount of time
6. Rewrite one loop-based solution using a comprehension without reducing readability.

## Submission Checklist

- [ ] All completed cells run without syntax errors.
- [ ] Outputs match the expected outputs.
- [ ] At least five exercises contain an additional student-created test case.
- [ ] Variables use meaningful names.
- [ ] Functions return values when requested.
- [ ] Strings, lists, NumPy arrays, tuples, sets, and dictionaries are used appropriately.
- [ ] Formatting and indentation are consistent.